### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by python-bookworm** [y00423502/pytorch_densnet121-classify#2]
博主你好，我尝试训练3个分类，报以下错误：
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [1,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "train.py", line 239, in <module>
    output_model= train_model(model, criterion, optimizer_ft, exp_lr_scheduler,num_epochs=opt.epochs)
  File "train.py", line 144, in train_model
    loss.backward()
  File "/home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: device-side assert triggered (host_softmax_backward at /pytorch/aten/src/ATen/native/cuda/SoftMax.cu:659)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x46 (0x7fced548b536 in /home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: at::Tensor at::native::(anonymous namespace)::host_softmax_backward<at::native::(anonymous namespace)::LogSoftMaxBackwardEpilogue, true>(at::Tensor const&, at::Tensor const&, long, bool) + 0x78b (0x7fced81a65ab in /home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #2: at::native::log_softmax_backward_cuda(at::Tensor const&, at::Tensor const&, long, at::Tensor const&) + 0x99 (0x7fced8191c59 in /home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0xf73540 (0x7fced685a540 in /home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0x10c4396 (0x7fcf131bd396 in /home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x2ca977c (0x7fcf14da277c in /home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #6: <unknown function> + 0x10c4396 (0x7fcf131bd396 in /home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #7: torch::autograd::generated::LogSoftmaxBackward::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x1c9 (0x7fcf1499e859 in /home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #8: <unknown function> + 0x2d89705 (0x7fcf14e82705 in /home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #9: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&) + 0x16f3 (0x7fcf14e7fa03 in /home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #10: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&, bool) + 0x3d2 (0x7fcf14e807e2 in /home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #11: torch::autograd::Engine::thread_init(int) + 0x39 (0x7fcf14e78e59 in /home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #12: torch::autograd::python::PythonEngine::thread_init(int) + 0x38 (0x7fcf217c0ac8 in /home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #13: <unknown function> + 0xbd6df (0x7fcf226706df in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #14: <unknown function> + 0x76db (0x7fcf246926db in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #15: clone + 0x3f (0x7fcf243bba3f in /lib/x86_64-linux-gnu/libc.so.6)

具体问题没有查到，期待回复，谢谢。

**Comment by python-bookworm** [comment]
博主的环境配置是怎样的？

**Comment by y00423502** [comment]
> 博主的环境配置是怎样的？

docker hub上面下载pytorch的镜像即可，选一个热度高的

**Comment by y00423502** [comment]
> 博主你好，我尝试训练3个分类，报以下错误：
> /pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [1,0,0] Assertion `t >= 0 && t < n_classes` failed.
> Traceback (most recent call last):
> File "train.py", line 239, in
> output_model= train_model(model, criterion, optimizer_ft, exp_lr_scheduler,num_epochs=opt.epochs)
> File "train.py", line 144, in train_model
> loss.backward()
> File "/home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/tensor.py", line 198, in backward
> torch.autograd.backward(self, gradient, retain_graph, create_graph)
> File "/home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/autograd/**init**.py", line 100, in backward
> allow_unreachable=True) # allow_unreachable flag
> RuntimeError: CUDA error: device-side assert triggered (host_softmax_backward at /pytorch/aten/src/ATen/native/cuda/SoftMax.cu:659)
> frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x46 (0x7fced548b536 in /home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/lib/libc10.so)
> frame #1: at::Tensor at::native::(anonymous namespace)::host_softmax_backward<at::native::(anonymous namespace)::LogSoftMaxBackwardEpilogue, true>(at::Tensor const&, at::Tensor const&, long, bool) + 0x78b (0x7fced81a65ab in /home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
> frame #2: at::native::log_softmax_backward_cuda(at::Tensor const&, at::Tensor const&, long, at::Tensor const&) + 0x99 (0x7fced8191c59 in /home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
> frame #3: + 0xf73540 (0x7fced685a540 in /home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
> frame #4: + 0x10c4396 (0x7fcf131bd396 in /home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
> frame #5: + 0x2ca977c (0x7fcf14da277c in /home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
> frame #6: + 0x10c4396 (0x7fcf131bd396 in /home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
> frame #7: torch::autograd::generated::LogSoftmaxBackward::apply(std::vector<at::Tensor, std::allocatorat::Tensor >&&) + 0x1c9 (0x7fcf1499e859 in /home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
> frame #8: + 0x2d89705 (0x7fcf14e82705 in /home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
> frame #9: torch::autograd::Engine::evaluate_function(std::shared_ptrtorch::autograd::GraphTask&, torch::autograd::Node*, torch::autograd::InputBuffer&) + 0x16f3 (0x7fcf14e7fa03 in /home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
> frame #10: torch::autograd::Engine::thread_main(std::shared_ptrtorch::autograd::GraphTask const&, bool) + 0x3d2 (0x7fcf14e807e2 in /home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
> frame #11: torch::autograd::Engine::thread_init(int) + 0x39 (0x7fcf14e78e59 in /home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
> frame #12: torch::autograd::python::PythonEngine::thread_init(int) + 0x38 (0x7fcf217c0ac8 in /home/rex-han/anaconda3/envs/yolo_pytorch/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
> frame #13: + 0xbd6df (0x7fcf226706df in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
> frame #14: + 0x76db (0x7fcf246926db in /lib/x86_64-linux-gnu/libpthread.so.0)
> frame #15: clone + 0x3f (0x7fcf243bba3f in /lib/x86_64-linux-gnu/libc.so.6)
> 
> 具体问题没有查到，期待回复，谢谢。

你这个不是代码报错，应该是环境问题，考虑pytorch版本等因素，我这个是在pytorch1.3的版本下做的，README我今天重新写份详细的，上次commit太匆忙了
